name: "Waveshare LCD Display Home Assistant Add-on"
description: "Support for a Waveshare 2 inch LCD display for Home Assistant"
version: "0.0.18"
slug: "waveshare_lcd_display_add_on"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
devices:
  - /dev/spidev0.0
  - /dev/spidev0.1
  # - /dev/gpiomem

